# Deploy to github pages on every commit
name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish to Github Pages
        run: npm run deploy
